import 'package:get/get.dart';

class LangManager extends Translations {
  Map<String, Map<String, String>> get keys => {
        'en': {
          '>': '>',
          '<': '<',
          'wellcomPageTitle1': 'SEE THE BEST COURSE #1',
          'wellcomPageTitle2': 'SEE THE BEST COURSE #2',
          'wellcomPageTitle3': 'SEE THE BEST COURSE #3',
          'wellcomPageTitle4': 'SEE THE BEST COURSE #4',
          'wellcomPageBody1':
              'Tut app is an awesome flutter application using clean architecture #1',
          'wellcomPageBody2':
              'Tut app is an awesome flutter application using clean architecture #2',
          'wellcomPageBody3':
              'Tut app is an awesome flutter application using clean architecture #3',
          'wellcomPageBody4':
              'Tut app is an awesome flutter application using clean architecture #4',
          'skipBtn': 'Skip',
          'usernameText': 'Username',
          'passwordText': 'Password',
          'loginBut': 'Login',
          'forgetBtn': 'Forget password',
          'notAMemberBtn': 'Not a member ? Sign up',
          'mobileText': 'Mobile number',
          'emailText': 'Email',
          'registerBtn': 'Register',
          'photoText': 'Photo',
          'aleardyHave': 'Already have an account ? Login',
          'resetPassText': 'Reset password',
          'dontReseveEmail': 'Didn’t recieve email ? Resesnd',
          'homeText': 'Home',
          'serviesText': 'Servies',
          'storiesText': 'Stories',
          'storiesTitle': 'Store details',
          'detalisText': 'Details',
          'aboutStoreText': 'About Store',
          'settingsText': 'Settings',
          'changeLanguageText': 'change language',
          'contactUsText': 'Contact Us',
          'inviteYourFriendsText': 'Invite your friends',
          'logoutText': 'Logout',
        },
        'ar': {
          '>': '<',
          '<': '>',
          'wellcomPageTitle1': 'مشاهدة أفضل كورس #1',
          'wellcomPageTitle2': 'مشاهدة افضل كورس #2',
          'wellcomPageTitle3': 'مشاهدة افضل كورس #3',
          'wellcomPageTitle4': 'مشاهدة افضل كورس #4',
          'wellcomPageBody1': 'هذا التطبيق يستخدم تقنية كتابة الكود النظيف 1',
          'wellcomPageBody2': 'هذا التطبيق يستخدم تقنية كتابة الكود النظيف 2',
          'wellcomPageBody3': 'هذا التطبيق يستخدم تقنية كتابة الكود النظيف 3',
          'wellcomPageBody4': 'هذا التطبيق يستخدم تقنية كتابة الكود النظيف 4',
          'skipBtn': 'تجاوز',
          'usernameText': 'اسم المستخدم',
          'passwordText': 'كلمة السر',
          'loginBut': 'تسجيل الدخول',
          'forgetBtn': 'نسيت كلمة السر',
          'notAMemberBtn': 'لا املك حساب؟ تسجيل الان',
          'mobileText': 'رقم الجوال',
          'emailText': 'البريد الالكتروني',
          'registerBtn': 'تسجيل',
          'photoText': 'الصورة',
          'aleardyHave': 'انا أملك حساب؟ تسجيل الدخول',
          'resetPassText': 'اعادة تعيين كلمة المرور',
          'dontReseveEmail': 'لم يتم ارسال الرمز',
          'homeText': 'الصفحة الرئيسية',
          'serviesText': 'الخدمات',
          'storiesText': 'القصص',
          'storiesTitle': 'معلومات القصة',
          'detalisText': 'معلومات',
          'aboutStoreText': 'عن المتجر',
          'settingsText': 'الاعدادات',
          'changeLanguageText': 'تغيير اللغة ',
          'contactUsText': 'اتصل بنا',
          'inviteYourFriendsText': 'دعوة الاصدقاء',
          'logoutText': 'تسجيل الخروج',
        },
      };
}
